variables:
  DOCKER_REGISTRY: 926377470665.dkr.ecr.us-east-2.amazonaws.com
  DEVOPS_IMAGE: devops-pipeline
  DEVOPS_IMAGE_VERSION: 1.6.0
  DEFAULT_APP_VERSION: latest
  APP_NAME: geek
  APP_VERSION: $CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
  IMAGE_TAG: $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
  PROJECT_DIR: $CI_PROJECT_DIR


stages:
  - build
  - test
  - publish
  - deploy-dev
  - deploy-prd


build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - npm install --save --legacy-peer-deps
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    # - npm run test
    - echo "Test successfully!"

publish:
  stage: publish
  variables:
    CONTEXT: $PROJECT_DIR
    DESTINATION: $IMAGE_TAG
    PROJECT_NAME: $CI_PROJECT_NAMESPACE
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  
  trigger: 
    include:
      - project: 'devops-team/image-publisher'
        ref: 'main'
        file: '/.gitlab-ci.yml'
    strategy: depend



deploy-dev:
  dependencies:
    - build
  stage: deploy-dev
  when: manual
  image:
    name: $DOCKER_REGISTRY/$DEVOPS_IMAGE:$DEVOPS_IMAGE_VERSION
  only:
    - dev      
  variables:
    NAMESPACE: ${APP_NAME}-dev
    RELEASE_NAME: ${APP_NAME}-dev
  script:
    - aws eks update-kubeconfig --name tt_k8s_cluster
    - helm upgrade --install -f helm/values-dev.yaml
      --set image.repository=${DOCKER_REGISTRY}/${APP_NAME}
      --set image.tag=${APP_VERSION}
      --set "ingress.hosts[0].host=${APP_NAME}.dev-apps.turntabl.io"
      --set "ingress.hosts[0].paths[0].path=/"
      --set "ingress.hosts[0].paths[0].pathType=ImplementationSpecific"
      --set "ingress.tlsName=${TLS_NAME_DEV}"
      --set "ingress.tlsCrt=${TLSCERT_DEV}"
      --set "ingress.tlsKey=${TLSKEY_DEV}"
      ${APP_CONFIG} --create-namespace -n ${RELEASE_NAME} ${RELEASE_NAME} ./helm
    - echo "Application URL=https://${APP_NAME}.dev-apps.turntabl.io"


deploy-prd:
  dependencies:
    - build
  stage: deploy-prd
  when: manual
  image:
    name: $DOCKER_REGISTRY/$DEVOPS_IMAGE:$DEVOPS_IMAGE_VERSION
  only:
    - main
  variables:
    NAMESPACE: ${APP_NAME}-prd
    RELEASE_NAME: ${APP_NAME}-prd
  script:
    - aws eks update-kubeconfig --name tt_k8s_cluster
    - helm upgrade --wait --install -f helm/values-prd.yaml
      --set image.repository=${DOCKER_REGISTRY}/${APP_NAME}
      --set image.tag=${APP_VERSION}
      --set "ingress.hosts[0].host=${APP_NAME}.apps.turntabl.io"
      --set "ingress.hosts[0].paths[0].path=/"
      --set "ingress.hosts[0].paths[0].pathType=ImplementationSpecific"
      --set "ingress.tlsName=${TLS_NAME_PRD}"
      --set "ingress.tlsCrt=${TLSCERT_PRD}"
      --set "ingress.tlsKey=${TLSKEY_PRD}"
      ${APP_CONFIG} --create-namespace -n ${RELEASE_NAME} ${RELEASE_NAME} ./helm
    - echo "Application URL=https://${APP_NAME}.apps.turntabl.io"
